# Generated by Django 4.0.6 on 2022-07-24 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinePayed', models.BooleanField(default=False)),
                ('payed_date', models.DateField()),
                ('loan', models.ForeignKey(db_column='loan', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libraryApp.loan')),
            ],
        ),
    ]
