# Generated by Django 4.0.6 on 2022-07-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='payed_date',
            field=models.DateField(null=True),
        ),
    ]
